# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag

image: uber/android-build-environment

# Accept all licences

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
           - mkdir -p "$ANDROID_HOME/licenses"
           - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
           - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
           - echo y | android update sdk --all --filter build-tools-24.0.0 --no-ui
           - echo y | android update sdk --filter "extra-android-m2repository" --no-ui -a
           - ./gradlew clean assemble --stacktrace